### ISSUE TITLE
Setup linter for this repo to run for all PRs

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp-prototype#10]
Using Black linter based on conversation with @mweiden and @bkmartinjr

**Comment by mweiden** [comment]
@maniarathi Yes, it worked a little better out of the box than `yapf`.

Here's some context that might be helpful to the person who takes on this issue:

**Comment by maniarathi** [comment]
Assigning to Trent because he's already work on it. Did you close the PR already? @Bento007

**Comment by Bento007** [comment]
fix by #22
