### ISSUE TITLE
Assess DCP1 projects to determine which require re-analysis

### ISSUE THREAD

**Issue by jychien** [HumanCellAtlas/dcp-prototype#103]
To determine which DCP1 projects need to be re-analyzed through pipelines:
1. Check for correct bundling of fastq files for each library
2. Check for correct matching of read1 and read2 files

**Comment by jychien** [comment]
Document that contains details of analysis:
https://docs.google.com/spreadsheets/d/1Qtbut2-yL2i7mPfN6gd154i255BzteX0gCTG9kPHOwc/edit?usp=sharing

**Comment by jahilton** [comment]
LGTM

**Comment by jychien** [comment]
**SUMMARY**: (cont.)
  - Additional project that has data and metadata incorrectly bundled: 
    - **_A single-cell molecular map of mouse gastrulation and early organogenesis_**: This dataset contains 10x v1 data, for which there is no current HCA approved pipeline. The current data organization results in  2560 libraries/bundles. The associated paper says there are 116,312 cells, which would mean there are about 45 cells per library. This is highly unlikely. It seems that the library_prep_id and process_id are incorrectly assigned and need to be re-evaluated. There needs to be more metadata in regards to which fastq files are associated with a specific channel on a 10x chip to really determine which fastq should be grouped together.
