### ISSUE TITLE
Create wrangling tools initial design document

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp-prototype#111]

**Comment by mweiden** [comment]
Don't mind the above notifications ^^. I was testing a script for Lia.

**Comment by maniarathi** [comment]
Document 1 of 2 is complete with Wrangling User Stories that will be fulfilled in M1 and M2: https://docs.google.com/document/d/1gOoSTkwldx32C1ReR0frW0_2XEHcJD479liqx-QUAeQ/edit?userstoinvite=jlz%40stanford.edu&ts=5e4f2884&actionButton=1#heading=h.t849jh3lwzxu

**Comment by maniarathi** [comment]
Hey @MDunitz, just wondering what the status of this ticket is; I know that you managed to copy over all the data to an S3 bucket but what's the status on the script getting checked in? Doesn't need to be perfect since we hopefully don't need to do it again, but probably safe to have it around just in case.

Also, just curious, what were the changes you made the script to make it run faster? Just threaded? And how quickly does it run?

Question for @ambrosejcarr: the S3 uri for most of the FASTQ/BAM/etc. files use the FQID as the filename instead of the old SRR1234567_0.fastq.gz. FQID I realize is a much longer filename and I realized that the link will be exposed in the browser directly to download. Do you have a preference whether we just use the old name ("SRR1234567_0.fastq.gz") or the fqid ("0e7b2404-c529-43fb-a55d-199a76caa860.2019-08-01T031948.896Z.fastq.gz")?

**Comment by maniarathi** [comment]
Design document was in progress here: https://docs.google.com/document/d/1hFGu4pOW-ovkSRRKQ5LWmmaEEiNXaLUF2pcFhcbpNHk/edit#

However, in light of new information/changing requirements, especially around the use of SnoVault for wrangling tools, this document has been marked as deprecated and this ticket will be closed as no further work is required here.
