### ISSUE TITLE
Validation requirements document

### ISSUE THREAD

**Issue by jlzamanian** [HumanCellAtlas/dcp-prototype#115]
Create a document that details the validation requirements for the submissions.

In order to ensure a coherent and consistent data corpus, submission validation is required for metadata, files, and the experimental graph. 

This is a companion document to the [wrangling requirements](https://docs.google.com/document/d/1h1LAwCtOdIrk2VCqqwLPl8hF4TH536uP4NfeMHSzb50/edit?ts=5e41a0ca#heading=h.a7g3udqjivyi) document.

[Validation Requirements](https://docs.google.com/document/d/1cR_uQQq7pcZYVXFrJe9dezZxBzBvWay50HNpsHw4bsI/edit#heading=h.3o0p89q44zy5)

**Comment by jlzamanian** [comment]
This is a supporting document for prototype issue #81.

**Comment by jahilton** [comment]
LGTM!
