### ISSUE TITLE
Assess and survey assays for comparable and harmonized experimental metadata

### ISSUE THREAD

**Issue by jychien** [HumanCellAtlas/dcp-prototype#120]
We need to capture comparable assay metadata to provide harmonized and comprehensive data. This requires an assessment of assays for multiple modalities and analysis of metadata fields.

**Comment by jychien** [comment]
**DOCUMENTS CONTAINING DETAILS:**

**Assay and library prep comparison ([spreadsheet](https://docs.google.com/spreadsheets/d/1XMulW_rGVT8H5APFczK490javQ2cCxeNwqT4g8rbZaA/edit?usp=sharing))**:
This is a spreadsheet containing comparative information summarizing multiple assays for various modalities. This includes variability in protocol and output, which could lead to unique metadata and analysis requirements.

**Assay and library prep comparison ([google drawing](https://docs.google.com/drawings/d/1b7eHqo0hBoTmQ3Eui59yW2WPlKHD6rCXelFDMqm8WzQ/edit?usp=sharing))**:
This is a diagram summarizing the various metadata captured that describes and is unique to specific assays. This allows for harmonized metadata to help provide structured organization and reduce ambiguity, enabling users to understand and interrogate the data corpus.

**Comment by jahilton** [comment]
This is great. I can use the linked docs to figure out how to capture the variation in metadata, and from there, iterate in the schema, as needed.
