### ISSUE TITLE
Resolve ontology terms to labels in API responses

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/dcp-prototype#127]
Use the OLS API to resolve ontology terms to labels before returning to the client.

**Comment by parthshahva** [comment]
This is still an open discussion between @ambrosejcarr and @jahilton as to whether the artifact will contain the id or term. 

Regardless @calvinnhieu, I don't think you should be doing the lookup before returning to the client. You should be doing the lookup during ETL and storing the value.

**Comment by calvinnhieu** [comment]
Fair - will follow up with @ambrosejcarr when that's decided. Created initially to provide real labels for tomorrow's demo and agree the long term solution is TBD.

Closing and will re-create when discussions have concluded.
