### ISSUE TITLE
Aggregate information on projects, files & metadata fields that will be used to categorize files and projects

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#14]
The first iteration of the DCP 2.0 data browser will enable users to browse projects. Consumers will be able to click on projects to find additional information and download files. Consumers will be able to download files that have been grouped by their values of the following metadata fields: File type, Species, Organ, and Assay type. The data browser will need the estimated number of cells for each file, and will need to know the sizes of each file. We want this information up front so we can make informed decisions about how to display the information, and most critically, how many groups of files we expect to need to serve for each project. 

*N.B.* we will probably need more metadata fields in the future -- if the process used to generate these data could be repeatable, that will likely save us time later. 

**AC:** 
---
- [ ] Create a json blob that contains the file size, file type, cell count, species, organ, and assay type for each file. This JSON blob should be suitable for serving from a mock API endpoint. File sizes can be approximated to the nearest suffix (b, kb, mb, gb, ...)
- [ ] It's unclear whether we will bundle the files in each category into tar balls or serve individual files. The json blob should have information on individual files that the team can later use to build aggregates.

**Comment by ambrosejcarr** [comment]
@mckinsel I spoke with @MDunitz about this ticket. 

@MDunitz agreed that query service would be the easiest way to get this information, but the query service has been taken down. To get this information we'd need to restart it and run the ETL, which would take about a week. She suggested that your short term plan to mock one or two projects for by hand to complete #17 made sense. 

We have an open question about whether we should stand up the query service to get this information or wait for the result of #8 and get it from the ledger. We should be mostly unblocked by #17, but this spike would help us identify edge cases earlier. @mckinsel What do you think makes the most sense?

**Comment by parthshahva** [comment]
@MDunitz I'm surprised we didn't take an RDS snapshot when taking down the cluster. This is best practice and quite inexpensive to leave it hanging around. This should really be done and kept around for a year even if we don't think we are going to utilize a service.
