### ISSUE TITLE
Migrate existing matrices from DCP 1.0 to use DCP 2.0 metadata schema fields

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp-prototype#144]
In order to ensure interoperability within the existing DCP dataset, ensure that matrices are also using the same metadata fields as dictated in DCP 2.0 metadata schema instead of the DCP 1.0 values.

Cell metadata listed here: https://docs.google.com/spreadsheets/d/1wAPWTk0rVTeEPE_ndKK7NvYNjO_99D-1gOmcKD6xq1U/edit#gid=0

**Comment by parthshahva** [comment]
We should not drop any values from the DCP 1.0 matrix for now if there is no direct mapping to 2.0. Lets keep a list of unmapped properties

**Comment by maniarathi** [comment]
We have copies of the DCP 1.0 matrices. Why keep around the unmapped properties in the ones that we surface to users via the browser?

**Comment by maniarathi** [comment]
@mckinsel has completed this per conversations last week so closing this ticket.
