### ISSUE TITLE
Create a mock API to serve the list of projects

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#15]
We'd like to develop a basic front end that matches the needs of realistic numbers of files and categories. For the cut-over, we anticipate needing an API endpoint that serves the list of projects present in a published artifact to support a "browsable projects" page. For now we'd like to mock that endpoint.

- **AC:** Mock GET endpoint for the list of projects. Returns a collection of projects and information on total file size, total cell count, and a list of species, organ, and assay type. Details on payload in #14

**Comment by mckinsel** [comment]
This is done, there's a `projects` endpoint that returns and array of objects that look like this:

```json
  {
    "short_name": "scRNAseqSystemicComparison",
    "title": "Systematic comparative analysis of single cell RNA-sequencing methods",
    "total_file_size": 59790,
    "id": "28",
    "assays": [
      "10X v2 sequencing",
      "10x v3 sequencing",
      "CEL-seq2",
      "DroNc-seq",
      "Drop-seq",
      "Seq-Well",
      "Smart-seq2",
      "inDrop",
      "sci-RNA-seq"
    ],
    "total_cells": 59790,
    "organs": [
      "blood",
      "brain"
    ],
    "species": [
      "Homo sapiens",
      "Mus musculus"
    ]
  },```
