### ISSUE TITLE
Can the browser serve data to someone who may not have authenticated with us?

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#152]
## Description

Pre-signing URLs are a way to prevent unauthenticated access by users. However, users can share those URLs with others who may not have authenticated. Users can also download the data and share it with other users directly, in which case we have done our due dilligence, and any potential misconduct lies with the user. However, with pre-signed URLs, a user can share the URL, and an un-authenticated user could then download the data directly from us. In this case, have we done the necessary due dilligence to ensure that we are requiring registration before allowing people to download data? 

- [ ] AC: Decision from Shawn on this question.

**Comment by Bento007** [comment]
The decision to this question was yes presign urls given to authenticated users is sufficient access control.
