### ISSUE TITLE
Design of the list-of-projects page

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#16]
Create a few options for how the projects page could look. 

**AC:**
---
- [x] design mocks for organization of projects page
- [x] decision on design

**Comment by liaprins-czi** [comment]
Here is where I'm starting to explore the list of projects, there are several pages within this Figma file (see far left sidebar to navigate them):
https://www.figma.com/file/LCBTk5cTkoOtW9IC5GfpeF/Browser-for-user-tests?node-id=15%3A0

I will add more specific links to prototypes as I create them and then narrow down from talking to SMEs and users.

**Comment by liaprins-czi** [comment]
Here's a list of questions (for SMEs + users) I have about the projects page, the answers to which will help to narrow down the design:
https://docs.google.com/document/d/1lTQTE-KcFy35FTdDWaT2Ob5fjWDXT-6v7CFoSsMcMMA/edit#heading=h.ueadiqp2cbro

It includes links to specific Figma prototypes that exemplify the options under consider for the design.

I've met with a few people internally to get their feedback, and will be typing up my notes from those sessions, here:
https://drive.google.com/open?id=1MwdmetBgF6_TJqMgmFICOypiIV6SdVYa

**Comment by liaprins-czi** [comment]
I have added action items to the synthesized notes from the internal feedback I've solicited. These are the next steps for solidifying the browser designs:
https://docs.google.com/document/d/1B7BNDvoxhnkU7vFSSc4kKPQWCp51dqpdzkHTVysMbLA/edit?usp=sharing

**Comment by ambrosejcarr** [comment]
As discussed on Friday, our goal with this initial prototype is to make sure we capture the user facing functionality of the existing DCP software. As part of this, I made a quick assumption early on that this would include the "checkout" capability of the browser. 

However, design discussions with @liaprins-czi and @colinmegill prompted me to revisit browser-based download of multi-files. I am no longer convinced it makes sense and would like to pause this feature to give some time for user research. You can see my reasoning [here](https://docs.google.com/document/d/1wzOMYFzgZsbLOvcPaPo0D4a3qdGnysf1eXJLSSjkGIA/edit#heading=h.bwuly3wdh661).

In the meantime, I would like to downscope on download. The browser need only: 
1. Enable downloading of matrix files and metadata.
2. Communicate to users how they can use the command line to download the rest of the files (sync with @Bento007 and @calvinnhieu on this).

and the back-end needs to: 
1. Create a very simple CLI interface to enable download of multiple files. I'd be fine with aws s3 sync for now. 

I will propagate this feature downscoping through the requirements and backlog.

**Comment by liaprins-czi** [comment]
Here is a link to the design prototype demoing how a user goes about downloading files. It includes designs for both the list-of-projects and the project page:
https://www.figma.com/proto/0kKMpYmqJuBpqDCmmunhBD/4-Browser?node-id=2%3A0&viewport=-20854%2C918%2C1&scaling=min-zoom

Here is a link to the Figma file itself, which includes several explanatory comments:
https://www.figma.com/file/0kKMpYmqJuBpqDCmmunhBD/4-Browser?node-id=0%3A1

![1 list-of-projects.png](https://images.zenhubusercontent.com/5d4c6939b2c9257cd301cec2/1159c0c6-6f3d-4741-9b66-32081839dd30)

**Comment by ambrosejcarr** [comment]
Being reviewed in #19
