### ISSUE TITLE
Create a mock API to serve information on files within a project

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#17]
When users click on an individual project, we'd like them to be able to get more information on that project and download the files. For now we're focusing on the download portion, and like to mock an endpoint that provides information on the files of a project.

**AC:** 
---
- [x] Mock project endpoint. Returns details on an individual project, including list of individual files and their sizes, cell counts, species, organ, and assay type. More details on payload in #14
- [x] Mock file downloads if actual data is present.

**Comment by Bento007** [comment]
The download file link be a link to an individual static file.

**Comment by ambrosejcarr** [comment]
@Bento007 to discuss with @liaprins-czi most likely download paths.

**Comment by Bento007** [comment]
The file endpoint has been mocked `https://ye54tu6ueg.execute-api.us-east-1.amazonaws.com/dev/project/{id}/{file}`
