### ISSUE TITLE
Determine the authentication-related user flows

### ISSUE THREAD

**Issue by liaprins-czi** [HumanCellAtlas/dcp-prototype#170]
- [x] Find out from Sean how much we can allow non-authenticated users to view:
- nothing
- list-of-projects page
- project page sans download file area
- all of project page including download area, but they must authenticate to get URLs

- [x] Document how the system and user will interact as a user flow

**Comment by liaprins-czi** [comment]
Here is the authentication flow; just need to find out how much we can show to unauthenticated users.
![authentication flow _small.jpg](https://images.zenhubusercontent.com/5d4c6939b2c9257cd301cec2/f8e8770c-1aa3-45f0-8b9a-36feaf869db7)

**Comment by liaprins-czi** [comment]
There are a few ways we could  let users onto the project page, but not download data:

1. Only let unauthenticated users see the Project Info at the top of the page; the Project Data section below that would be covered/hidden and replaced by a message + link to authenticate
2. Let unauthenticated users see the Project Data but not make selections until they authenticate
3. Same as 2 but users can make selections, we only make them authenticate when/before they can click to the “Generate URLs” button

Here’s what #1 could be like:
https://www.figma.com/proto/1kdqXjSGfgfCRTHgAKHuWM/Authentication?node-id=311%3A5165&viewport=-1559%2C466%2C0.25&scaling=min-zoom
User can still scroll down to the Project Data section. From there it woudl direct them to the login/sign up screen. But if they click the “Project Data” anchor link in the left nav, it could automatically take them to the log in/sign up screen instead. Then once they authenticate, it automatically redirects them to the Project Data portion of the project page.

**Comment by mweiden** [comment]
> Find out from Sean how much we can allow non-authenticated users to view

I think @ambrosejcarr may have the answer to this.

**Comment by ambrosejcarr** [comment]
We almost certainly don't need authentication for legal or ethical reasons
unless we're sharing nucleotide data (bam, fastq) that we host.

Authentication will be very useful for us for telemetry and as an "above
and beyond" measure to protect against future identifiability based on
count data.

The current design proposal is here:
https://www.figma.com/proto/1kdqXjSGfgfCRTHgAKHuWM/Authentication?node-id=311%3A5165&viewport=-1559%2C466%2C0.25&scaling=min-zoom

**Comment by mweiden** [comment]
@liaprins-czi @Bento007 Bit of added clarification I gleaned here: the registration modal should open up when the user clicks `Project Data`.
