### ISSUE TITLE
Incorporate non-DCP dataset into Artifact

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp-prototype#173]
Pick a dataset among:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE71585
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60361
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE93374
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE76381

Extract metadata, transform metadata into artifact specification, output to JSON, and upload matrix to artifact location (?).

**Comment by mckinsel** [comment]
Per @ambrosejcarr 's suggestion, working on this one: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60361 .

It's ~3k mouse cells.

**Comment by mckinsel** [comment]
Artifact at s3://dcp-test-artifacts/Artifact.Mar18.json has GSE60361 dataset
