### ISSUE TITLE
Identify cXg metadata for the matrix files referenced in the Artifact

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/dcp-prototype#175]
[**March 20 Demo Action Items**](https://docs.google.com/presentation/d/1nY4PXzOEs8euFEAlp2dHxB5dMZTZLSuinXzOo_eR7Ig/edit#slide=id.p4)

Identify cXg metadata (20 fields?) for the matrix files referenced in the Artifact

---

**References**:

[matrix cell metadata [from Core schema & usage [2/18/2020]]](https://docs.google.com/spreadsheets/d/1wAPWTk0rVTeEPE_ndKK7NvYNjO_99D-1gOmcKD6xq1U/edit#gid=0)

**Comment by brianraymor** [comment]
@mckinsel and @jahilton - Has the list been finalized? For example, is the Reference in the top-level comment accurate?

**Comment by jahilton** [comment]
The list in the Reference would be my proposal to use.

**Comment by mckinsel** [comment]
The list in the reference spreadsheet has many fields we don't have, and there are actually two different sets of fields labeled "matrix cell metadata", so it's not clear to me what it would mean to use it.

What we have is this, which is roughly an intersection of the two dcp/2 field lists and what we have in dcp/1:

```
biosample_preparation.donor_species
biosample_preparation.organ
biosample_preparation.donor_development_stage_at_collection
biosample_preparation.donor_diseases
biosample_preparation.donor_ethnicity
biosample_preparation.donor_accession
biosample_preparation.donor_sex
biosample_preparation.biosample_category
project.project_title
```

**Comment by jahilton** [comment]
>...field we don't have

Assuming you mean the _DCP_ doesn't have them, then you are correct. Migration will be necessary for some. Calculated fields will also be necessary for some. So it depends on what is/is not included in the demo.


>there are actually two different sets of fields labeled "matrix cell metadata"

I intended for those checked "matrix cell metadata" on the "Core schema summary" tab to match the top row on the "matrix cell metadata" tab. Just realized there are 3 that I forgot to clear from the latter. Apologies for the inconsistency, I have marked them in red.
`library_preparation_protocol.library_construction_method`
`biosample_preparation.cell_isolation_method`
`library_preparation_protocol.nucleic_acid_source`

**Comment by mckinsel** [comment]
Oh yeah, to be clear I mean "not in dcp/1 matrices", which is an even stronger constraint. I can pretty easily add library construction method and nucleic acid source. I think cell isolation would require some digging through the dcp/1 jsons, though. Okay if we hold off on that one for the next demo?

**Comment by jahilton** [comment]
Ya, no problem

**Comment by mckinsel** [comment]
The matrices with that set of metadata are in `s3://demo-matrices`
