### ISSUE TITLE
Incorporate DCP/1 datasets into Artifact

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/dcp-prototype#176]
[**March 20 Demo Action Items**](https://docs.google.com/presentation/d/1nY4PXzOEs8euFEAlp2dHxB5dMZTZLSuinXzOo_eR7Ig/edit#slide=id.p4)

- [x]  Marcus to write script to update cXg metadata in matrices (Loom format)
- [x]  Brian M  to write  DCP/1 project metadata  [bypassing Ledger]
---

**Comment by bmccandless** [comment]
The v.0.0.0 artifact is ready to be consumed.  
It contains only the project metadata, and not files information.

There may be changes to make to the artifact.  In particular the flattening of all the fields loses some potentially useful information.   Jason commented on this in the DCP-2 slack channel.
https://chanzuckerbergteam.slack.com/archives/CS66X37CZ/p1583430918047400

**Comment by jahilton** [comment]
Summarizing my comments from Slack: The artifact schema flattens all metadata within a project. This may suffice for the upcoming demo, but is insufficient for actual consumption use cases that will need to understand the metadata at a finer resolution, as to not be constrained by how the submitter grouped data together. I suggested flattening within a library, which is the general idea behind the biosample_preparation object.

Specific issues:
- what the artifact labels `biosample_categories` is actually what is intended for `biosample_name`. See the [biosample_preparation doc](https://docs.google.com/document/d/175TbHFZ1CUIK_CT8t4G05FDQRe9LlRP7qIeG8MiWzCg/edit) for details.
- `"id": "091cf39b-01bc-42e5-9437-f419a66c8a45"` has no `donor_species`
- no projects have `selected_cell_markers`. I would expect some to have that (from enrichment_protocol.markers)

**Comment by bmccandless** [comment]
Hi Jason

Thanks for the review.  I am working on fixes now.

1.   I'm not sure how to get biosample_category.   From the document it should be a value like 'primary tissue', 'organoid', 'cell line'.   What's the best way to deduce that from DCP1 metadata?


2.  The project with missing donor_species. (Human-Hematopoietic-Profiling)
The script is expecting to read from ontology_label, which is missing:  e..g

 "genus_species": [
  {
   "text": "Homo sapiens",
   "ontology": "NCBITaxon:9606"
  }
 ],

I could add in some special cases to handle this.

3.  selected_cell_markers.  I have it fix.  It was a bug in the script.

**Comment by jahilton** [comment]
1. biosample_category is directly dependent on `the last non-suspension biomaterial in the graph`. Unsure how you're looking at the graph but you want to find the process that has output of a cell_suspension, and then look at the input to that process.

2. OK, that's a metadata error, no need to add a special case for that.

**Comment by bmccandless** [comment]
I've updates the migration scripts to address Jason's comments.
I've attached a new artifact.  


[https://app.zenhub.com/files/228681195/6bbcf22f-f68c-4f1c-98d6-a9aa3a6d8a25/download](https://app.zenhub.com/files/228681195/6bbcf22f-f68c-4f1c-98d6-a9aa3a6d8a25/download)

**Comment by mckinsel** [comment]
Artifact with DCP/1 datasets is at s3://dcp-test-artifacts/Artifact.Mar18.json

**Comment by jychien** [comment]
@bmccandless I found some additional issues:

1. **"organs"**: needs to reflect the organ of the biosample that was sequenced (last non-suspension biomaterial. For example, "_HPSI human cerebral organoids_" should have organs be "_brain_". "_skin of body_" and "_stem cell_" were organs of biomaterials that were created along the way in the experiment and should not be listed.
2. **"biosample_diseases"**: needs to reflect the disease of the biosample that was sequenced (last non-suspension biomaterial). For example, "_Drop-seq, DroNc-seq, Fluidigm C1 Comparison_" is a cell line experiment and does not have *.diseases.text for the cell line. For the artifact, "_biosample_diseases_" field is currently listed as "_normal_" and should be empty.
3. **"cell_isolation_methods"**: this field does not exist in DCP1. It describes the assay used to isolate and label cells (eg: "_Fluidigm C1_" for "_HumanColonicMesenchymeIBD_"). Can be just left empty for the time being.
4. **"protocols_io_doi"**: is supposed to list all protocols_io_doi from DCP1 _*.protocol_core.protocols_io_doi_, but is currently empty
5. **"project_description"**: from DCP1 _project.project_core.project_description_, but is missing from artifact
