### ISSUE TITLE
Choose DCP datasets to run on pBAM pipeline

### ISSUE THREAD

**Issue by jahilton** [HumanCellAtlas/dcp-prototype#184]
Running the pipeline on a sample dataset for purpose of evaluating if information is lost/distorted in the pBAM process

For each dataset, a new ticket will be made that will include...
- [ ] Choose DCP1 dataset (human + 10X)
- [ ] Process dataset
- [ ] Process dataset w/ pBAM
- [ ] Compare outputs of the 2 processes, and each with findings from the published results

**Comment by jahilton** [comment]
First step towards selecting a DCP1 dataset: list the possible datasets and the tissue(s) sampled for each.
Need to 'fit' the Optimus pipeline, should be human to be relevant for the pBAM work, publication is ideal but not required.

**Comment by jychien** [comment]
**Diagram of possible DCP1 dataset**: https://docs.google.com/drawings/d/1H2fNDYAFuCx--1pY6yNFgh7zw3W7p5Ws5lLuFB_d_r0/edit

**Summary:**
 - 11 HCA projects with 10x 3' v2 data
 - 3 HCA projects with Smart-seq2 paired end data
 - 2 HCA projects with 10x 3' v3 data (no matrix available)

**Comment by jahilton** [comment]
@jychien can you add a human/mouse column? (since mouse data aren't applicable to pBAM)
if a project is mixed, maybe separate the mouse/human data into separate columns

**Comment by jychien** [comment]
I've updated to colors on the diagram to help clarify. The 3 dark blue boxes from the diagram is further elucidated in the table below, which means only human 10x 3' v2, 10x 3' v3, and SS2 portions of projects were outlined. Also have separated 'Fetal/Maternal Interface' rows per assay.

**Comment by jahilton** [comment]
As we are not going to run multiple datasets, I have converted this ticket to the selection.
@jychien will provide an update here and create new tickets for each selected dataset

**Comment by jychien** [comment]
Current datasets that have been chosen:

1. **SS2 pancreas**: [Single cell transcriptome analysis of human pancreas](https://data.humancellatlas.org/explore/projects/cddab57b-6868-4be4-806f-395ed9dd635a) DID_scRSq04_pancreas and DID_scRSq06_pancreas have been chosen as the 2 donors. [Issue #196](https://github.com/HumanCellAtlas/dcp-prototype/issues/196)
2. **10x v2**: [SingleCellLiverLandscape](https://data.humancellatlas.org/explore/projects/4d6f6c96-2a83-43d8-8fe1-0f53bffd4674) P2TLH_liver and P3TLH_liver have been chosen as the 2 donors. [Issue #197](https://github.com/HumanCellAtlas/dcp-prototype/issues/197)

The following issue needs to be resolved:

3. **10x v3**: It has been requested that an HCA dataset be used. [HDCA-Sweden-10x](https://data.humancellatlas.org/explore/projects/008e40e8-66ae-43bb-951c-c073a2fa6774). This dataset has the following unresolved issues below. Will look into the 10x v3 dataset from [scRNAseqSystemicComparison](https://data.humancellatlas.org/explore/projects/88ec040b-8705-4f77-8f41-f81e57632f7d)
    -  Fastq files seem to be on the smaller side (MB rather than GB).
    -  Read1 is 26bp, and should be strictly at least 28bp ([link](https://support.10xgenomics.com/single-cell-gene-expression/index/doc/specifications-sequencing-requirements-for-single-cell-3)). 
    -  Further spot-checking analysis showed that cell barcodes corresponds with v2 cell barcode whitelist.

**Comment by jychien** [comment]
Will close this ticket as individual tickets have been created for each dataset. (@jahilton)

**Comment by jahilton** [comment]
We still need to decide Dataset 3, right?

**Comment by jychien** [comment]
Yes, thanks for the reminder, I'll make a ticket for Dataset 3. The only possibility left is scRNAseqSystemicComparison, but I'll need to assess the quality as it wasn't run through the pipelines in DCP1. It'll track the progress for Dataset 3 in [Issue #202](https://github.com/HumanCellAtlas/dcp-prototype/issues/202)
