### ISSUE TITLE
Prototype script to migrate DCP 1.0 metadata to DCP 2.0 metadata

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp-prototype#2]
Tasks:
- [x] Migrate FASTQs, BAMs, and matrices while maintaining project UUIDs.
- [x] Migrate metadata.

Acceptance Criteria:
- [ ] Validate that all DCP 1.0 MD is translatable to DCP 2.0 metadata schema.
- [ ] Manual verification and sign-off by Stanford.

**Comment by maniarathi** [comment]
Tasks:
- [ ] Migrate FASTQs, BAMs, and matrices while maintaining project UUIDs.
- [ ] Migrate metadata.

Acceptance Criteria:
- [ ] Manual verification and sign-off by Stanford.

**Comment by maniarathi** [comment]
2019-01-30 Update:

The data model that will be used for conversation is based off of the diagram here: https://drive.google.com/drive/u/0/folders/17IQl9BVvnkcvpgxcWMk_wfGGf6zC8_om starting from the BiosamplePrep node as the root node.

I attempted to first import DCP 1.0 spreadsheets into the new data model but ran into issues programmatically reading in the spreadsheets as they are unstandardized in format. Will be switching to using the JSON metadata files.

**Comment by brianraymor** [comment]
The objective is to migrate one project during Sprint 1 (Feb 7) and then re-assess whether to parallelize the remaining projects across engineers.

**Comment by maniarathi** [comment]
First draft of best effort metadata-only conversion sits here. These spreadsheets will be used to validate the conversion (manually) by the data ops team: https://drive.google.com/drive/u/0/folders/1gMTWUFSoFaCyjfbFcAdiYItHqXLCuJqe

Blockers/Next Steps:
- [Blocker] Need to figure out what constitutes as a "unique key" for each entity in DCP 1.0. Each entity will be assigned an HCA-accession moving forward but we need a way to answer the question "what defines a unique library preparation protocol" for example. 
- [Blocker] Need to figure out where each foreign key lives for any relationships between the entities. I make educated guesses right now but this will also be a blocker for setting up the relational DB. For example, do projects contain a foreign key "contributor id" or do contributors contain a foreign key "project id"?
- [Next step] Codify the different mappings of DCP 1.0 metadata to BiosamplePrep. Currently, I use a "best-guess" only for datasets that are qualified as "primary specimen". Then classify each dataset into its category so that the appropriate metadata is generated.
- [Next step] Figure out where the fastqs for the projects live and as a final run, copy the file to a new S3 bucket while keeping track of the link for population in the SequenceFile entity.

**Comment by maniarathi** [comment]
Update: migration of the full pancreas dataset is in progress and you can see the files being uploaded to the ledger in this S3 bucket here: https://s3.console.aws.amazon.com/s3/buckets/dcp-ledger-bucket-dev/single_cell_transcriptome_analysis_of_human_pancreas_metadata/?region=us-east-1&tab=overview

This takes a while because of the de-duping and the loading to S3 and there isn't any parallelization yet (sorry, didn't write a MapReduce) so should take about 20 hours or so for the full dataset to be in. Once all the files are into S3, the population of the ledger DB itself won't take that long and is also easy to remedy if it fails.

Blocker: need matrix (loom) file for the project which is on @mckinsel todo list, I believe. Also need the respective values for Quantification Protocol that will connect the analysis files and expression matrix together.

**Comment by maniarathi** [comment]
Script prototyping is complete and we've moved on to making it more robust and performant for the migration of the entire DCP 1.0 data.
