### ISSUE TITLE
Identify the metadata fields needed to populate the project page

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#24]
We want to create project pages for the web browser that are similar to the DCP 1.0 pages ([example](https://data.humancellatlas.org/explore/projects/005d611a-14d5-4fbf-846e-571a1f874f70)). We want to generate these pages programmatically from the metadata that we gather from contributors. 

**AC:** 
---
- [x] Create a list of proposed information that should be on each project page, discuss with UX & PM, and make a decision on what is needed. 
- [ ] Add information to the artifact spec

**Comment by jahilton** [comment]
@jychien already has a head-start on this

**Comment by brianraymor** [comment]
See [browser metadata tab](https://docs.google.com/spreadsheets/d/1d6Pi8Lph_QUxDIyIQG_JrzkkOrfTspikqwzNvCzqWbk/edit#gid=1892162826) in metadata matrix.

**Comment by ambrosejcarr** [comment]
We should use the document linked by @brianraymor as the metadata for the first iteration of the end-point.
