### ISSUE TITLE
Create a new endpoint or extend the project mock API endpoint to serve information on an individual project

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#25]
In addition to serving information on the matrix file(s) and related metadata within a project, the browser wishes to populate the information on the project programmatically. See this [example](https://data.humancellatlas.org/explore/projects/005d611a-14d5-4fbf-846e-571a1f874f70). Once we know which fields are important to send to users (#24), we should create a mock endpoint (or extend #17) that the browser can develop against.

**AC:** 
---
- [x] Create a mock endpoint whose payload contains all the information needed to populate a basic project page.

**Comment by Bento007** [comment]
Blocked by #24

**Comment by Bento007** [comment]
mock complete
