### ISSUE TITLE
Document Published Artifact

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/dcp-prototype#28]
- [ ] v0 json schema specification

**Comment by parthshahva** [comment]
Created at https://docs.google.com/document/d/1WglovQ5rBnIS2aBKmnd4oolC3tX9Z4A8FPBXNpH7lZY/edit

**Comment by brianraymor** [comment]
Re-opening. This is a _draft 0_ with pending comments. Is there a timeline for addressing or resolving comments?

**Comment by parthshahva** [comment]
All comment threads have been resolved except for one. I don't believe there is anything actionable on the last remaining thread so waiting for a response.

This is for M1 however. There will be additional changes for M2/M3 to reflect lifecycle, cellxgene, and additional browser requirements

**Comment by parthshahva** [comment]
This ticket now represents the conversion of the artifact schema to jsonschema

**Comment by parthshahva** [comment]
WIP at https://github.com/HumanCellAtlas/dcp-prototype/pull/158

**Comment by mckinsel** [comment]
Closed by bdd7bee4dee128103d10c29f8556ad7d34a0e5a3
