### ISSUE TITLE
Prototype how DCP 2.0 metadata should be represented in the ledger DB

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp-prototype#3]
Tasks:
- [x] AWS account setup
- [x] Infra setup: DB
- [x] Initial prototyping around schema representation, migrations, ORMs

Acceptance Criteria:
- [x] Live DB available with initial version of schema with mock data entry.

**Comment by parthshahva** [comment]
https://github.com/HumanCellAtlas/dcp-prototype/pull/55 ready for review. Dev db is online and available for testing

**Comment by mweiden** [comment]
@parthshahva @maniarathi seems like this ticket is should be closed? If not, what remains to be done?
