### ISSUE TITLE
"hosted" dev build/deploy of cellxgene

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#38]
Development/demo deployment build and packaging of cellxgene hosted on AWS/EB.  Includes compression, CORS, etc.

Much of the configuration and patterns can be borrowed from the cxg-tiledb prototype repo.

End result will be ability, by any party with an AWS account, to build & deploy the cellxgene repo into EB, resulting in the same features as the current proto site.

- [x] WSGI app
- [x] A Makefile target to build the application deployment zip
- [x] Makefile target to build the EB dev configuration (allowing user to `eb deploy`) for a "dev" environment
- [x] Cursory/starter documentation of the WSGI app configuration (eg, CXGDATAROOT environment variable), and brief build/deploy process (eg, in `dev_docs` or a README or whatever is convenient).

**Comment by bmccandless** [comment]
I've pushed a PR for this:  https://github.com/chanzuckerberg/cellxgene/pull/1200/commits

**Comment by bkmartinjr** [comment]
This tracking issue is completed.  The config subsystem was moved to #203
