### ISSUE TITLE
refactor cellxgene repo for multiple backend deployments

### ISSUE THREAD

**Issue by bkmartinjr** [HumanCellAtlas/dcp-prototype#57]
Refactor/reorganize the cellxgene repo, build system and backend framework to support multiple builds/deployments/backends, while maintaining the current CLI/H5AD functionality.

**Comment by mweiden** [comment]
@bkmartinjr @bmccandless I see that https://github.com/chanzuckerberg/cellxgene/pull/1140 is merged. Does that mean that this ticket can be closed?

**Comment by bmccandless** [comment]
@mweiden @bkmartinjr I just closed the cellxgene@1140 issue

**Comment by bkmartinjr** [comment]
Yes, I'll close.  We are at 98% (do not yet have multiple builds, but I  plan to add those as part of #38).
