### ISSUE TITLE
Determine an authentication method

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/dcp-prototype#61]
Write a specification that describes how users will authenticate given the decision to use Auth0. 

- [x] AC: describes what identity(ies) users can use
- [x] AC: describes how users will authenticate in the browser
- [x] AC: describes how users will authenticate from the command line. 
- [ ] AC: Includes TOS (get from Shawn)

**Comment by Bento007** [comment]
# describes what identity(ies) users can use
Auth0 is the authenticator we are going with. We still need to decide what authentication providers to user. Previously we use google. We can use any SAML, or Oauth2 provider with Auth0.

# describes how users will authenticate in the browser
For our the browser we will use Oauth2 Authorization code flow which is supported by Auth0. Oauth2 Implicit flow is not longer recommended for SPA (single page application). 

For long user sessions, the browser can silently refresh the token using auth0/authorization endpoint with query parameter `prompt=none`, as long as the user still has the auth0 session cookie present.

# describes how users will authenticate from the command line.
For the short term it sounds like only curl with presigned urls will be used to access data. In the future a cli tool can be built to authenticate and download files for the user.

**Comment by Bento007** [comment]
# Logout in Browser
Logout from the browser can be performed by clearing the access_token stored in a browser cookie, and the auth0 sessions cookie.
