### ISSUE TITLE
Deploy Browser

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/dcp-prototype#67]
## User story
* As a user
* I want to view the browser from my computer
* so that I can find projects I care about.

## Definition of done
* Automate deployment of website to AWS using terraform

## Notes
@colinmegill if you can link the resources to generate the browser files that would be appreciated.

**Comment by ambrosejcarr** [comment]
@Bento007 were you able to get the information on browser files you needed to unblock this work?

**Comment by Bento007** [comment]
yep
