### ISSUE TITLE
Deploy backend

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/dcp-prototype#68]
## User story

* As a developer
* I want to a reproducible process for deploying the browser backend 
* so that I can continuously deploy new features quickly.

## Definition of done
* Setup terraform to deploy backend code
* at minimum the Swagger spec should deployed to API Gateway after every commit to master

**Comment by ambrosejcarr** [comment]
@Bento007 @calvinnhieu It feels like this should be blocked on a ticket to "create the back-end", but I don't see a ticket tracking that work. Do we need to make one that outlines the ACs for the back end for this sprint?

**Comment by calvinnhieu** [comment]
@ambrosejcarr that makes sense - rather this ticket seems to capture two separate concerns: 1. that our AWS infra should be managed by Terraform and 2. the creation of a CI/CD pipeline. IMO, (1) should be captured in tickets to create backend components (e.g. #77) and this ticket can be revised to capture (2).

**Comment by Bento007** [comment]
adding ticket for Continuous deployment work. https://app.zenhub.com/workspaces/dcp2-5e2a191dad828d52cc78b028/issues/humancellatlas/dcp-prototype/147
