### ISSUE TITLE
Design browser database schema

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/dcp-prototype#76]
Design a database schema to index the required project and file metadata to support the browser.

Requirements:
- Enables querying of projects by assay, organ and species fields
- Enables querying of files by assay, organ and species fields
- Stores sufficient metadata about projects and files to render Project List and Project Detail pages
- Stores sufficient metadata about files to enable download of files

**Comment by calvinnhieu** [comment]
[Schema design doc](https://docs.google.com/document/d/1BaMxK7NNe5tRHN9x5FTOrS-5BeZUJdlzfSMuFGdyTJk/edit?usp=sharing)

**Comment by ambrosejcarr** [comment]
@calvinnhieu  I quickly reviewed the design doc. I tried to address your open questions. My hope is we can assume 1:1 relationships for file:{organ, species, assay} for now. If not, I'd like to know why and see if we can problem solve. 

When you've cleaned up the todos, I suggest that when you sit with @liaprins-czi and confirm that it contains all the information needed for her prototype. If she signs off, consider it reviewed for content. 

I leave it to you to determine who should review it on the tech side beyond Marcus.

**Comment by calvinnhieu** [comment]
Great - moving ahead with 1:1 relationships between file:{organ, species, assay} until it's no longer true. Reviewing with @jahilton , @liaprins-czi , @mckinsel and @parthshahva to finalize today.
