### ISSUE TITLE
Populate browser database from mock artifact

### ISSUE THREAD

**Issue by calvinnhieu** [HumanCellAtlas/dcp-prototype#78]
Write simple ETL scripts from a mock artifact's TSV files (project.tsv, files.tsv) to populate all tables

**Comment by ambrosejcarr** [comment]
@calvinnhieu do you imagine this work will be reviewed in another ticket?

**Comment by calvinnhieu** [comment]
Ah, good point. I suppose this is being reviewed now with Colin's work. Will bring into QA/Review
