### ISSUE TITLE
Parallelize script to read in metadata files for a project and transform the metadata graph into entities to submit to the Ledger DB.

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp-prototype#85]
As part of the effort to migrate DCP 1.0 data into DCP 2.0 and convert the metadata schema into the DCP 2.0 metadata schema, the end-to-end conversion occurs in two steps:

1) First, the full set of bundles for a single project is downloaded to an EC2 instance following which a script reads, each file in the bundle, determines whether it has been previously copied to an S3 bucket via checksum, and if not, copies the file over to an S3 bucket in the DCP 2.0 AWS account. The files are "flattened" which means that it no longer only exists in its bundle directory so that duplicates may be removed. This process also allows us to retain a lossless copy of all DCP 1.0 data.

2) Once all the data for a project has been copied and de-duped into a single folder in an S3 bucket, a script reads each file, and if it is related to constructing the metadata graph for the project (these are all the .json files), reads the entity into a Python object. Once all entities have been read, all links.json files are read to construct the edges between the Python objects that have been created. Following this, the metadata graph is transformed into entities that can be directly inputted into the Ledger using the DCP 2.0 metadata schema.

This ticket refers specifically to part 2 of the above process. This script has no parallelization and takes 2-3 hours for a dataset that contains ~2500 bundles with relatively small files. This will need to be sped up to be able to be sustainable for larger projects and to aid quick turnover when the Ledger DB changes and DCP 1.0 needs to be migrated again.

A couple areas for improvement include: parallelizing the reading of entities prior to the reading of `links.json` files. Another idea could be to transform and commit each entity as it is being read followed by the population of the join tables after the `links.json` files have been read.

**Comment by mweiden** [comment]
@maniarathi @bmccandless this ticket is done, no? https://github.com/HumanCellAtlas/dcp-prototype/pull/110

**Comment by bmccandless** [comment]
Yes, I think we can call it done.   There is more that can be parallelized, but likely we'd be getting diminishing returns.   If I need to speed it up further then I can open a new ticket.
