### ISSUE TITLE
Survey contributor analysis products for DCP1 projects

### ISSUE THREAD

**Issue by jahilton** [HumanCellAtlas/dcp-prototype#90]
Task: Locate & assess processed/analysis data products pertaining to the existing projects.

While gathering HCA stakeholder feedback, we heard a lot of support for the DCP to start taking contributor processing/analysis products. This task will also help the DCP start to get a general understanding of what kind of variation we will experience (file formats, references, software, etc.) and can lead to standards and a schema. This will also facilitate the submission of those products once the DCP is capable of hosting them.

**Comment by jychien** [comment]
**Assessment of DCP1 projects:** https://docs.google.com/spreadsheets/d/1Qtbut2-yL2i7mPfN6gd154i255BzteX0gCTG9kPHOwc/edit?usp=sharing

**SURVEY OF DCP1**:
This tab lists the current projects in DCP1 and the following information:
- **_DCP1 URL_**
- **_DCP1 Matrix for entire project_**: 
There is a matrix for the entire project (value == TRUE), or there is raw sequence data that does not have a corresponding matrix  (value == FALSE).
- **_Broad pipeline available for non-analyzed data_**: 
All data has been analyzed (value == NA), there is no approved Broad pipeline for the non-analyzed data (value == FALSE), or there is an open ticket to run data through pipelines (value == ticket_url from secondary_analysis)
- **_Matrix available in public domain_**: 
There is a matrix available for download in an public repository (value == TRUE), or the matrix for the project is unavailable in the public domain (value == FALSE)
- **_Publication_**: 
There is no publication available for project (value == NA), there is no publication listed in the project page but a publication has been found (value is written in red), or there is a publication found (value == url)
- **_Public domain accession_**: Accessions where data from the project is available 


**DEEP DIVE**:
This tab lists 3 projects where the analysis process and products were evaluated and summarized. Analysis products include alignment, quantification, expression, dimensionality reduction, cell, cluster, and QC metrics.

**Comment by jahilton** [comment]
I was able to find 4 publications for ones that were marked otherwise (at least I think I did). Those should be verified & see if they point to a matrix in the public domain. The relevant cells are marked in read and publications are linked in the **Months since published** column

**Comment by jahilton** [comment]
@jychien , please also double-check the details I left in the **Broad pipeline available for non-analyzed data** column for _why_ it can't be run.

**Comment by jahilton** [comment]
Thanks!
