### ISSUE TITLE
Update the submitter survey

### ISSUE THREAD

**Issue by jahilton** [HumanCellAtlas/dcp-prototype#95]
Task: A focused review of the submission survey and update it in order to ensure that it meets these needs while also remaining a non-intimidating first action for the contributor.

The first interaction between the DCP and data generators is crucial. The data survey provided to the data generator should be thorough enough for the DCP to get a solid grasp on the experiment leading to the data generation, and ideally, fill in much of the metadata and identify which parts of the schema won’t be appropriate for the specific data contribution. 
Existing DCP1 ticket that may have some ideas: https://github.com/HumanCellAtlas/hca-data-wrangling/issues/300

- [ ] Discuss with wranglers 2/6/20

**Comment by jlzamanian** [comment]
Closing this due to the unlikelihood of Stanford wrangling community data submissions.
